#############################################################################
# Makefile for building: subtivals
# Generated by qmake (2.01a) (Qt 4.7.0) on: ven. juil. 22 12:51:22 2011
# Project:  subtivals.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile subtivals.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		script.cpp \
		style.cpp \
		event.cpp \
		subtitlesform.cpp \
		configdialog.cpp moc_mainwindow.cpp \
		moc_script.cpp \
		moc_style.cpp \
		moc_event.cpp \
		moc_subtitlesform.cpp \
		moc_configdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		script.o \
		style.o \
		event.o \
		subtitlesform.o \
		configdialog.o \
		moc_mainwindow.o \
		moc_script.o \
		moc_style.o \
		moc_event.o \
		moc_subtitlesform.o \
		moc_configdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		subtivals.pro
QMAKE_TARGET  = subtivals
DESTDIR       = 
TARGET        = subtivals

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_subtitlesform.h ui_configdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: subtivals.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile subtivals.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile subtivals.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/subtivals1.0.0 || $(MKDIR) .tmp/subtivals1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/subtivals1.0.0/ && $(COPY_FILE) --parents mainwindow.h script.h style.h event.h subtitlesform.h configdialog.h .tmp/subtivals1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp script.cpp style.cpp event.cpp subtitlesform.cpp configdialog.cpp .tmp/subtivals1.0.0/ && $(COPY_FILE) --parents mainwindow.ui subtitlesform.ui configdialog.ui .tmp/subtivals1.0.0/ && (cd `dirname .tmp/subtivals1.0.0` && $(TAR) subtivals1.0.0.tar subtivals1.0.0 && $(COMPRESS) subtivals1.0.0.tar) && $(MOVE) `dirname .tmp/subtivals1.0.0`/subtivals1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/subtivals1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_script.cpp moc_style.cpp moc_event.cpp moc_subtitlesform.cpp moc_configdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_script.cpp moc_style.cpp moc_event.cpp moc_subtitlesform.cpp moc_configdialog.cpp
moc_mainwindow.cpp: script.h \
		style.h \
		event.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_script.cpp: style.h \
		event.h \
		script.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) script.h -o moc_script.cpp

moc_style.cpp: style.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) style.h -o moc_style.cpp

moc_event.cpp: event.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) event.h -o moc_event.cpp

moc_subtitlesform.cpp: event.h \
		subtitlesform.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) subtitlesform.h -o moc_subtitlesform.cpp

moc_configdialog.cpp: configdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) configdialog.h -o moc_configdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_subtitlesform.h ui_configdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_subtitlesform.h ui_configdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_subtitlesform.h: subtitlesform.ui
	/usr/bin/uic-qt4 subtitlesform.ui -o ui_subtitlesform.h

ui_configdialog.h: configdialog.ui
	/usr/bin/uic-qt4 configdialog.ui -o ui_configdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		script.h \
		style.h \
		event.h \
		subtitlesform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		script.h \
		style.h \
		event.h \
		ui_mainwindow.h \
		configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

script.o: script.cpp script.h \
		style.h \
		event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o script.o script.cpp

style.o: style.cpp style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o style.o style.cpp

event.o: event.cpp event.h \
		script.h \
		style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o event.o event.cpp

subtitlesform.o: subtitlesform.cpp subtitlesform.h \
		event.h \
		ui_subtitlesform.h \
		style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o subtitlesform.o subtitlesform.cpp

configdialog.o: configdialog.cpp configdialog.h \
		ui_configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o configdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_script.o: moc_script.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_script.o moc_script.cpp

moc_style.o: moc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_style.o moc_style.cpp

moc_event.o: moc_event.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_event.o moc_event.cpp

moc_subtitlesform.o: moc_subtitlesform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_subtitlesform.o moc_subtitlesform.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

